### ISSUE TITLE
Running Matcher(type='message', module=nonebot_plugin_forwarder, lineno=10) failed.

### ISSUE THREAD

**Issue by BHBNSN** [ninthseason/nonebot_plugin_forwarder#14]
Running Matcher(type='message', module=nonebot_plugin_forwarder, lineno=10) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/CACXsage/.venv/lib/python3.8/site-packages/nonebot/__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "/root/CACXsage/.venv/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/CACXsage/.venv/lib/python3.8/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/CACXsage/.venv/lib/python3.8/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/CACXsage/.venv/lib/python3.8/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/CACXsage/.venv/lib/python3.8/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/CACXsage/.venv/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/CACXsage/.venv/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 817, in simple_run
    await handler(
  File "/root/CACXsage/.venv/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/CACXsage/.venv/lib/python3.8/site-packages/nonebot_plugin_forwarder/__init__.py", line 33, in _
    await asyncio.wait(tasks)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 413, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.

**Comment by N0rth5ea** [comment]
当源群和发送群相同时触发此报错
