### ISSUE TITLE
插件加载报错

### ISSUE THREAD

**Issue by Dr-WeiAL** [ninthseason/nonebot_plugin_forwarder#6]
```
D:\bot\NoneBot\WeiAL-Bot>nb run
12-22 23:59:57 [SUCCESS] nonebot | NoneBot is initializing...
12-22 23:59:57 [INFO] nonebot | Current Env: prod
12-22 23:59:57 [ERROR] nonebot | Failed to import "nonebot_plugin_forwarder"
Traceback (most recent call last):
  File "c:\weial\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\weial\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\WeiAL\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\weial\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\weial\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\weial\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\weial\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\weial\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\weial\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\weial\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "c:\weial\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\bot\NoneBot\WeiAL-Bot\.\bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "c:\weial\python38\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "c:\weial\python38\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "c:\weial\python38\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "c:\weial\python38\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "c:\weial\python38\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "c:\weial\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\weial\python38\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\bot\NoneBot\WeiAL-Bot\.\weial_bot\plugins\nonebot_plugin_forwarder\__init__.py", line 7, in <module>
    from nonebot.params import State
ImportError: cannot import name 'State' from 'nonebot.params' (c:\weial\python38\lib\site-packages\nonebot\params.py)
```
大概就到这里了，本来是直接在商店用命令安装的，发现不能用之后来这里手动放进去还是不能用

**Comment by ninthseason** [comment]
推测是与nonebot2最新版本不兼容，已修改。
插件最新版本2.0.5。

**Comment by Dr-WeiAL** [comment]
好的能加载了
话说现在有添加显示群昵称的计划吗(

**Comment by ninthseason** [comment]
> 好的能加载了 话说现在有添加显示群昵称的计划吗(

已添加功能
插件最新版本2.1.5，详细使用方法见README

**Comment by Dr-WeiAL** [comment]
> > 好的能加载了 话说现在有添加显示群昵称的计划吗(
> 
> 已添加功能 插件最新版本2.1.5，详细使用方法见README

好的谢谢，不过我发现了一个bug，当群员没有设置群名片的时候，使用群名片模式不显示任何东西
![image](https://user-images.githubusercontent.com/47446553/209269542-1423354a-e507-421a-915f-153f37ae15d9.png)
或许添加一个检测群名片为空的时候显示昵称比较好？

**Comment by ninthseason** [comment]
#7
